include:
  - project: consensys/codefi/infrastructure/gitlab-templates
    ref: v4.1.1
    file: common/workflow.yml
  - project: consensys/codefi/infrastructure/gitlab-templates
    ref: v4.1.1
    file: common/build-us.yml
  - project: consensys/codefi/infrastructure/gitlab-templates
    ref: v4.1.1
    file: common/scan-us.yml
  - project: consensys/codefi/infrastructure/gitlab-templates
    ref: v4.1.1
    file: common/tag-us.yml
  - project: consensys/codefi/infrastructure/gitlab-templates
    ref: v4.1.1
    file: common/push-us.yml

variables:
  IGNORE_AUDIT: "true"
  SONARQUBE_ALLOW_FAILURE: "true"
  NODE_IMAGE: core-harbor.eu-west-3.codefi.network/proxy_cache/library/node:14
  DOCKER_REGISTRY_PASSWORD: "$FOUNDATION_DOCKER_REGISTRY_PASSWORD"
  DOCKER_REGISTRY_USER: "robot$$foundation-bot"
  DOCKER_REGISTRY: "core-harbor.eu-west-3.codefi.network"

stages:
  - build
  - scan
  - push
  - tag
