# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: node:14

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public
    - yarn
    - yarn dist
    - cp -r dist/* public
    - cp dist/index.html dist/404.html
  tags:
    - eu-west-3
  artifacts:
    paths:
      - public
  only:
    - master
