name: Validate PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        rm -rf public
        mkdir public
        yarn
        yarn build
        cp -r dist/* public
        cp dist/index.html dist/404.html 

  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: "high"
        vulnerability-check: true